### PR TITLE
Added: Custom installation directory support

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Added: Bash ordering convention
Test: ./start.sh /e/Documents/Bach-Projs/InstallSteamCMD ( MINGW64 )

### CODE REVIEW

**Comment by Gousaid67** [comment]
ok read it thx for the help man

**Comment by Gousaid67** [comment]
i will merge it

**Comment by Gousaid67** [comment]
i renamed it steamcmdinstaller3.8 because i found it to not work properly

**Comment by dvdvideo1234** [comment]
Which part does not work ??

**Comment by Gousaid67** [comment]
the part that didnt worked was throught my testing was first the <<<<<<<<HEAD>>>>>>> d6fb2765024afb4d20a8cd567ae235a491ebb78d  part is it return as an error,also between those two line the code was duplicated,you left the old line of code,i dont know which distro you tested on it but i tested everything in ubuntu so it might be the cause. if you can tell me which distro you used to test  i could fix those

**Comment by Gousaid67** [comment]
oh w8 ik why the mergng had a bug

**Pull request merged**
