### PR TITLE
Preformed: Code factorization via getInput()

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Added: md5 check-sum support
Added: HL1 CS1.6 mods handling when $appid=90

### CODE REVIEW

**Comment by Gousaid67** [comment]
thx man

**Comment by Gousaid67** [comment]
im gonna test it later

**Comment by Gousaid67** [comment]
kk thx dude srly the thing you just made is beyond what i can currently do XD

**Comment by dvdvideo1234** [comment]
No worries, that's the Git for ;)

**Comment by Gousaid67** [comment]
:D

**Comment by Gousaid67** [comment]
is it okay if i share you chksum techniques with someone else?

**Comment by dvdvideo1234** [comment]
Yeah, sure

**Comment by Gousaid67** [comment]
just a question why did you choosed the Getinput Function over the read command?

**Comment by dvdvideo1234** [comment]
I did not ditch the read "command", the "getInput" function uses it. It just reads the input until the user gives a value, as we cannot make a directory with empty name ;)

I just replaced the repeating code with the function "getInput". That way if you want to change something in the user-exit, you will not have to modify it at 20 places individually. And the most impotrant thing is that the script is shorter as it is ;)

**Comment by Gousaid67** [comment]
Ok so it replaces the read and the if test ( -z "$var" ), thats useful

**Comment by dvdvideo1234** [comment]
Yes, that's correct

**Comment by Gousaid67** [comment]
cool

**Pull request merged**
